use_frameworks!

platform :ios, '11.0'

target 'LLUIKit_Example' do
  
  pod 'LLUIKit', :path => '../'

#  target 'LLUIKit_Tests' do
#    inherit! :search_paths
#
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#  end
end
